const { createModel } = require('../lib/supabaseModel');
const { ORDER_STATUS, PAYMENT_METHODS, PAYMENT_STATUS } = require('../utils/constants');

const Order = createModel({
  name: 'Order',
  table: 'orders',
  collection: 'orders',
  mapping: {
    _id: 'id',
    id: 'id',
    service_type: 'service_type',
    price: 'price',
    client_name: 'client_name',
    client_phone1: 'client_phone1',
    client_phone2: 'client_phone2',
    address_text: 'address_text',
    address_coords: 'address_coords',
    pickup_address_text: 'pickup_address_text',
    pickup_address_coords: 'pickup_address_coords',
    pickup_contact_name: 'pickup_contact_name',
    pickup_contact_phone: 'pickup_contact_phone',
    pickup_notes: 'pickup_notes',
    clientNotes: 'client_notes',
    client_notes: 'client_notes',
    service_price: 'service_price',
    delivery_fee: 'delivery_fee',
    route_distance_km: 'route_distance_km',
    route_duration_min: 'route_duration_min',
    route_pricing_source: 'route_pricing_source',
    image_url: 'image_url',
    verification_code: 'verification_code',
    created_by_admin: 'created_by_admin',
    assigned_to_driver: 'assigned_to_driver',
    offered_to_driver: 'offered_to_driver',
    driver_offer_status: 'driver_offer_status',
    driver_offer_expires_at: 'driver_offer_expires_at',
    driver_offer_rejected_ids: 'driver_offer_rejected_ids',
    restaurantId: 'restaurant_id',
    restaurant_id: 'restaurant_id',
    restaurantStatus: 'restaurant_status',
    restaurant_status: 'restaurant_status',
    restaurantReadyAt: 'restaurant_ready_at',
    restaurant_ready_at: 'restaurant_ready_at',
    restaurantPrepTimeMin: 'restaurant_prep_time_min',
    restaurant_prep_time_min: 'restaurant_prep_time_min',
    partnerConfirmedAt: 'partner_confirmed_at',
    partner_confirmed_at: 'partner_confirmed_at',
    partnerConfirmedBy: 'partner_confirmed_by',
    partner_confirmed_by: 'partner_confirmed_by',
    pickupAuthorizedAt: 'pickup_authorized_at',
    pickup_authorized_at: 'pickup_authorized_at',
    pickupAuthorizedBy: 'pickup_authorized_by',
    pickup_authorized_by: 'pickup_authorized_by',
    partner_id: 'partner_id',
    purchase_source_type: 'purchase_source_type',
    purchase_source_label: 'purchase_source_label',
    purchase_source_coords: 'purchase_source_coords',
    requested_product: 'requested_product',
    publicAccessTokenHash: 'public_access_token_hash',
    client: 'client',
    status: 'status',
    timestamp_started: 'timestamp_started',
    timestamp_completed: 'timestamp_completed',
    pickupStartAt: 'pickup_start_at',
    pickupCompletedAt: 'pickup_completed_at',
    deliveryStartAt: 'delivery_start_at',
    deliveryCompletedAt: 'delivery_completed_at',
    driverAssignedAt: 'driver_assigned_at',
    driver_assigned_at: 'driver_assigned_at',
    lastStatusAt: 'last_status_at',
    last_status_at: 'last_status_at',
    cancelledAt: 'cancelled_at',
    cancelledBy: 'cancelled_by',
    cancelReason: 'cancel_reason',
    valor_motorista: 'valor_motorista',
    valor_empresa: 'valor_empresa',
    payment_method: 'payment_method',
    payment_status: 'payment_status',
    payment_confirmed_amount: 'payment_confirmed_amount',
    payment_confirmation_requested_at: 'payment_confirmation_requested_at',
    payment_confirmed_at: 'payment_confirmed_at',
    driver_delivery_notes: 'driver_delivery_notes',
    createdAt: 'created_at',
    updatedAt: 'updated_at'
  },
  defaults: {
    status: ORDER_STATUS.PENDING,
    price: 0,
    service_price: 0,
    delivery_fee: 0,
    route_distance_km: 0,
    valor_motorista: 0,
    valor_empresa: 0,
    payment_method: PAYMENT_METHODS.CASH,
    payment_status: PAYMENT_STATUS.UNPAID,
    payment_confirmed_amount: 0,
    pickup_contact_name: '',
    pickup_contact_phone: '',
    pickup_notes: '',
    clientNotes: '',
    driver_delivery_notes: '',
    offered_to_driver: null,
    driver_offer_status: null,
    driver_offer_expires_at: null,
    driver_offer_rejected_ids: [],
    restaurantStatus: null,
    partnerConfirmedAt: null,
    partnerConfirmedBy: null,
    pickupAuthorizedAt: null,
    pickupAuthorizedBy: null,
    partner_id: null,
    purchase_source_type: null,
    purchase_source_label: '',
    purchase_source_coords: null,
    requested_product: ''
  },
  relations: {
    created_by_admin: {
      model: () => require('./User'),
      localField: 'created_by_admin',
      foreignField: '_id',
      single: true
    },
    assigned_to_driver: {
      model: () => require('./DriverProfile'),
      localField: 'assigned_to_driver',
      foreignField: '_id',
      single: true
    },
    offered_to_driver: {
      model: () => require('./DriverProfile'),
      localField: 'offered_to_driver',
      foreignField: '_id',
      single: true
    },
    client: {
      model: () => require('./Client'),
      localField: 'client',
      foreignField: '_id',
      single: true
    },
    cancelledBy: {
      model: () => require('./User'),
      localField: 'cancelledBy',
      foreignField: '_id',
      single: true
    }
  }
});

module.exports = Order;
